[package]
name = "nodo_async"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6"
log = "0.4"
tokio = { version = "1", features = ["full", "tracing"] }
