[workspace]
resolver = "2"
  "examples",
  "inspector",
  "inspector_proto",
  "nodo",
  "nodo_async",
  "nodo_core",
  "nodo_derive",
  "nodo_json",
  "nodo_nng",
  # "nodo_record",
  "nodo_std",
]

[workspace.dependencies]
inspector_proto = { path = "inspector_proto" }
prost = "0.10"
